---
- hosts: 127.0.0.1
  connection: local

  roles:
    - {role: fcitx, become: yes}
    - {role: sublime3, become: yes}
    - {role: zsh, become: yes}
    - {role: sublime-add-chinese-support, become: yes}
    - {role: openjdk-8, become: yes}
    - {role: git, become: yes}
    - {role: docker, become: yes}
    - {role: tree, become: yes}
    - {role: vagrant, become: yes}
    - {role: pip3, become: yes}
    - {role: python-env, become: yes}
    - {role: mysql, become: yes}
    - {role: unity-tweak-tool, become: yes}
    - {role: compiz, become: yes}
    - {role: flash-player, become: yes}
    - {role: powerline-fonts, become: yes}
