---
  - name: install Vagrant
    apt:
      name: vagrant
      state: present
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install virtualbox-5.1.14
    apt:
      deb: http://download.virtualbox.org/virtualbox/5.1.14/virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb
