---
  - name: install python dev tools
    apt: name={{ item }} state=present
    with_items:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install python virtualenv
    apt:
      name: python3-venv
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
