---
  - name: install compiz
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - compiz
      - compizconfig-settings-manager
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
